# -*- coding: utf-8 -*-
"""Decesion Tree Classifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qPxo_KvtfLes8S7zLRX2BHFSXWuRSQb_
"""

import numpy as np

import pandas as pd

data=pd.read_csv('/content/Iris.csv')

data.info()

data.shape()

features=['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']
Prediction=['Species']

X=data[features].values
Y=data[Prediction].values

from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3)

from sklearn.tree import DecisionTreeClassifier

clf=DecisionTreeClassifier()

clf.fit(X_train,Y_train)

Y_predict=clf.predict(X_test)

from sklearn import metrics

print('Accuracy score;',metrics.accuracy_score(Y_test,Y_predict)*100,"%")

